### ISSUE TITLE
Quick start link not working

### ISSUE THREAD

**Issue by FedeClaudi** [JuliaDocs/DemoCards.jl#117]
Hey, not sure if you're aware but the `QuickStart` link in the README: https://johnnychen94.github.io/DemoCards.jl/stable/quickstart/ 

gives a 404 error

**Comment by FedeClaudi** [comment]
I'm guessing it should link to: https://juliadocs.github.io/DemoCards.jl/stable/

**Comment by johnnychen94** [comment]
4c30fdf775ef0a2b20687d6acb5f62f3df69f6d8
