### ISSUE TITLE
Support Pluto.jl notebooks for demos?

### ISSUE THREAD

**Issue by Dsantra92** [JuliaDocs/DemoCards.jl#120]
It would be nice to have DemoCards working with Pluto.jl. I was planning to use it for demos in [GraphNeuralNetworks.jl](https://github.com/CarloLucibello/GraphNeuralNetworks.jl).

ps: I will be happy to contribute to the feature (if approved).

**Comment by johnnychen94** [comment]
There are two ways to bring Pluto into this package:

- starting from a normal Julia script, then generating the pluto Julia script, and finally provides the pluto Julia script as an alternative to the current ipynb notebook version?
- export HTML from source pluto Julia script and insert into the generated index page

The first solution requires Litearte support (https://github.com/fredrikekre/Literate.jl/pull/120). For the second solution, is there a stable Pluto API to export HTML (or markdown files) here? I don't use Pluto much so don't know if this is doable.

**Comment by johnnychen94** [comment]
You can maybe start with a runtime dispatch to generate a new type `PlutoCard`: https://github.com/JuliaDocs/DemoCards.jl/blob/e2fc229fb4880fd90c9775698fa592d2737a3c37/src/types/card.jl#L20-L30 Then add the necessary `save_democards` function https://github.com/JuliaDocs/DemoCards.jl/blob/e2fc229fb4880fd90c9775698fa592d2737a3c37/src/types/julia.jl#L134-L142

Some special handling might be needed to directly insert the HTML into the template without passing it to Documenter's HTML generation. For instance, DemoCards uses Documenter's [`[](@ref id)` syntax](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@ref-link) to generate the reflink. For Pluto notebook, we might need a conditional check to insert the relative path instead.

**Comment by Dsantra92** [comment]
Thanks for the headstart!!
