### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by henry2004y** [JuliaDocs/DemoCards.jl#144]
The link
https://github.com/JuliaDocs/DemoCards.jl/blob/53ac68a4caafc62b5e02ddf5817204d26d2e8d00/docs/quickstart/usage_example/julia_demos/1.julia_demo.jl#L72
is not working properly.

**Comment by frankier** [comment]
Should be fixed now. These will get caught when error checking changes to strict in Documenter 1.0
